apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: welcome-prod
resources:
- ../../base/
patchesJson6902:
- path: deployment.yaml
  target:
    group: apps
    kind: Deployment
    name: welcome-app
    version: v1
