apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: build-trigger
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  params:
  - name: git-repo-name
    description: The name of the deployment to be created / patched
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName:  welcome-app-pipelinerun-
      annotations:
        argocd.argoproj.io/compare-options: IgnoreExtraneous
        argocd.argoproj.io/sync-options: Prune=false
    spec:
      serviceAccountName: pipeline
      pipelineRef:
        name: welcome-app-pipeline
      params:
        - name: GIT_REPO
          value: http://developer:openshift@gitea.scm.svc.cluster.local:3000/developer/welcome-app
        - name: GIT_REF
          value: main
        - name: IMAGE_DEST
          value: image-registry.openshift-image-registry.svc:5000/welcome-pipeline/welcome-app
        - name: SRC_DOCKERFILE
          value: Containerfile
        - name: DEPLOY_REPO
          value: http://developer:openshift@gitea.scm.svc.cluster.local:3000/developer/welcome-deploy
        - name: DEPLOY_REF
          value: main
        - name: DEV_OVERLAY_DIR
          value: dev
        - name: PROD_OVERLAY_DIR
          value: prod
      workspaces:
        - name: welcome-app-ws1
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 1Gi
        - name: scratch
          emptyDir: {}
