apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: welcome-app
  name: welcome-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: welcome-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: welcome-app
    spec:
      containers:
      - image: PATCH_ME
        name: welcome-app
        resources: {}
status: {}
